### ISSUE TITLE
Can't seem to get CustomEnchantments to work

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#13]
I put in a few custom enchantments in customenchantment.yml, file reloaded with no errors, but the plugin refuses to acknowledge that they exist, and I can't do /ce add or /ce book with them. Even when I get a book by using the GUI, it doesn't work when I try to apply it, and breaks the item that it is applying onto even when it has 100% success rate. Also, I did make sure the spaces were right, I put this in quotes as putting it in code completely messes up the format.

My config:
>#Potion Effect Names to pick from: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
Enchantments:
  Sniper: #Enchantment
    Name: 'Sniper' #The in-game name of the enchantment
    Color: '&c' #The color of the enchantment on the item
    BookColor: '&c&l' #The color of the enchantment on the book
    MaxPower: 4 #Max lvl the enchantment goes up to
    Categories: #All the categories the Enchantment can be found in
      - 'T3'
    EnchantOptions: #Customizing Options for each enchantment.
      ItemsEnchantable: 'Bows' #You can pick from Armor, Boots, Helmets, Axes, Swords, Weapons(Swords & Axes), and Bows.
      BowOptions: #Options that only effect Bow Enchantments.
        OnHit: #When the arrow Hits.
          #Remove the # to use the Exploding option.
          #Ground: #Options if the arrow hits the ground.
          #  Explode: #Options for the explosion.
          #   Power: 2 #The power of the explosion.
          #    PowerIncrease: 2 #How much each lvl will increases the strength.
          #    Chance: 25 #Chance of the arrow exploding.
          Damaged: #The player that is attacked.
            PowerIncrease: 1 #How many times the Potion Effects go up each lvl.
            PotionEffects: #Effects that are added to the Damaged.
            - 'HARM:1, Time:1, Chance:3'
  NatureWrath: #Enchantment
    Name: 'Nature Wrath' #The in-game name of the enchantment
    Color: '&c' #The color of the enchantment on the item
    BookColor: '&c&l' #The color of the enchantment on the book
    MaxPower: 4 #Max lvl the enchantment goes up to
    Categories: #All the categories the Enchantment can be found in
      - 'T3'
    EnchantOptions: #Customizing Options for each enchantment.
      ItemsEnchantable: 'Weapons' #You can pick from Armor, Boots, Helmets, Axes, Swords, Weapons(Swords & Axes), and Bows.
      WeaponOptions: #Options that only effect Sword and Axe Enchantments.
        #Remove the # to use the Damager options.
        #Damager: #The player with the sword.
        #  PowerIncrease: 1 #How many times the Potion Effects go up each lvl.
        #  PotionEffects: #Effects that are added to the Damager.
        #    - 'REGENERATION:2, Time:10, Chance:25'
        Damaged: #The player that is attacked.
          DamageMultiplyer: #The Damager Multipler Option.
            PowerIncrease: 1 #How many times the Multiplier will go up each lvl.
            Multiplyer: 2 #How many times stronger the attack is.
            Chance: 5 #The chance of the multiplier happening.
          #Remove the # to use the Potion options.
          PowerIncrease: 1 #How many times the Potion Effects go up each lvl.
          PotionEffects: #Effects that are added to the Damaged.
          - 'WITHER:1, Time:7, Chance:1'
          - 'POISON:1, Time:7, Chance:1'
          - 'CONFUSION:1, Time:10, Chance:1'
          - 'BLINDNESS:1, Time:10, Chance:1'
          - 'SLOWNESS:3, Time:10, Chance:1'<

**Comment by Yukun99** [comment]
The < at the end is not in the original file.

**Comment by kicjow** [comment]
Next time please put files like this in pastebin. You can not have an enchantment name with a Space.
Name: 'Nature Wrath'

**Comment by kicjow** [comment]
@Yukun99 Please tell me if this fixed it. If so close the issue. Other wise please tell me if your still having problems.

**Comment by Yukun99** [comment]
Alright trying it now, give me a moment haha, I just updated the plugin :P

**Comment by Yukun99** [comment]
I'm getting this error now :P
`[21:12:37] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SwarmEnchantments v1.5.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_91]
	at me.BadBones69.CrazyEnchantments.ECControl.Enchants(ECControl.java:37) ~[?:?]
	at me.BadBones69.CrazyEnchantments.ECControl.pick(ECControl.java:160) ~[?:?]
	at me.BadBones69.CrazyEnchantments.GUI.onInvClick(GUI.java:150) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
	... 15 more`

**Comment by kicjow** [comment]
You are going to need to upload your code to Github or something so i can see your lines. But from what I am looking at it looks like something in your config mite be missing. Check line 160 of your code.

**Comment by Yukun99** [comment]
Ok, I'm uploading... there are some weird class files when I just copy paste the code out though haha

**Comment by Yukun99** [comment]
Like, there are weird class files in the file system :P

**Comment by Yukun99** [comment]
The zipped one is here:
https://www.dropbox.com/s/jrbj3lthr1k4cxv/SourceCode.zip?dl=0
The whole system if you want to view before downloading is here:
https://www.dropbox.com/sh/c6oav4ojaozegii/AABEHGaX67vdbT0xHl4fT5Lta?dl=0

**Comment by Yukun99** [comment]
Do help me check my guardians code too :P, it might be what's killing the plugin D:

**Comment by Yukun99** [comment]
So this works now... weird, but normal enchants don't work, that thread is already here, so I'll close this one :D
