### ISSUE TITLE
InventoryClickEvent Failure

### ISSUE THREAD

**Issue by ChansinTech** [kicjow/Crazy-Enchantments#137]
I get this error message every time I try to click one of the green, blue, or red glass panes in the GUI:

`[18:42:30] [Server thread/INFO]: Chansin issued server command: /ce
[18:42:31] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1853) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_111]
	at me.BadBones69.CrazyEnchantments.Controlers.EnchantmentControl.Enchants(EnchantmentControl.java:57) ~[?:?]
	at me.BadBones69.CrazyEnchantment`

**Comment by Yukun99** [comment]
Did you edit your config?

**Comment by ChansinTech** [comment]
Yes, but I reinstalled the plugin and I still got the error.

**Comment by kicjow** [comment]
It seems one of your categories are empty. Can you pastebin your config.yml and enchantments.yml

**Comment by ChansinTech** [comment]
Sure thing.
http://pastebin.com/Qk4pFMEz
http://pastebin.com/jZCAGpV9

**Comment by kicjow** [comment]
@ChansinTech you didn't set the new category names in the Enchantments.yml. Here is a fix.
http://pastebin.com/JFqAJVab
