### ISSUE TITLE
Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.4

### ISSUE THREAD

**Issue by LuckyLoly** [kicjow/Crazy-Enchantments#142]
I know I probably messed up something in the Enchantments.yml or Gkitz.yml cause I was configuring them and I can't open any gkits and a lot of enchants aren't working so.
[EDIT]:I fixed the enchants not working, So it's probably the glitz.yml

 [18:43:37 ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1586) [spigot.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-13716d9-0899683]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-13716d9-0899683]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at me.BadBones69.CrazyEnchantments.API.GKitz.reloadKits(GKitz.java:181) ~[?:?]
	at me.BadBones69.CrazyEnchantments.API.GKitz.getGKit(GKitz.java:433) ~[?:?]
	at me.BadBones69.CrazyEnchantments.API.GKitz.giveKit(GKitz.java:443) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Controlers.GKitzGUI.onInvClick(GKitzGUI.java:117) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-13716d9-0899683]
	... 14 more

**Comment by LuckyLoly** [comment]
Nvm I found the problem

**Comment by LuckyLoly** [comment]
Nvm Still not working

**Comment by kicjow** [comment]
Could you pastebin your GKitz.yml for me.

**Comment by ItsFricco** [comment]
I have the same error, ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.4.1
org.bukkit.event.EventException, but when i try to veiw all enchantments from the gui. Is there a way to fix this or is my enchantments.yml the error?

**Comment by LuckyLoly** [comment]
I found the problem now, I messed something up when trying to create a gkit so I have that fixed.
