### ISSUE TITLE
Clicking in inventory GUIs doesnt work, tells me server is outdated when its newest offered version.

### ISSUE THREAD

**Issue by QQLazors** [kicjow/Crazy-Enchantments#15]
I'm having the following issue with any time I attempt to click anything on an inventory GUI. This is on Spigot 1.9.4 with no other plugins, with version 1.5.2:
Hopefully I'm just stupid and its an easy fix.

`[17:24:30 ERROR]: [Crazy Enchantments]>> Your server is to far out of date.Please update or remove this plugin to stop ferther Errors.
[17:24:32 ERROR]: [Crazy Enchantments]>> Your server is to far out of date.Please update or remove this plugin to stop ferther Errors.
[17:24:32 ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.5.2
org.bukkit.event.EventException
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1851) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
  at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
  at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.IllegalArgumentException: Item cannot be null
  at org.apache.commons.lang.Validate.noNullElements(Validate.java:364) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftInventory.addItem(CraftInventory.java:274) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  at me.BadBones69.CrazyEnchantments.GUI.onInvClick(GUI.java:150) ~[?:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
  ... 15 more
>`

**Comment by kicjow** [comment]
Thank you I have not yet updated to 1.9.4 yet. Thats why. Ill make a fix asap.

**Comment by QQLazors** [comment]
Oh, thank you! That would explain it.
