### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by matt-malle** [kicjow/Crazy-Enchantments#166]
I'm getting this spam in console basically any time I click something.

Using the latest version of CE, using Paper Spigot - 1.10.2

`[10:59:47 ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.6.3.4
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-916.2]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916.2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1909) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-916.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[patched_1.10.2.jar:git-Paper-916.2]
        at me.BadBones69.CrazyEnchantments.Methods.color(Methods.java:48) ~[?:?]
        at me.BadBones69.CrazyEnchantments.Controlers.Scrambler.onInvClick(Scrambler.java:254) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor724.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-916.2]
        ... 16 more`

**Comment by kicjow** [comment]
Please pastebin ur Config.yml

**Comment by kicjow** [comment]
Fixed on spigot because he was missing the Scrambler stuff from his Config.yml.
