### ISSUE TITLE
can't open enchant info from the menu

### ISSUE THREAD

**Issue by zetyu** [kicjow/Crazy-Enchantments#170]
I'm getting this error trying to open the enchant info in the menu :
[14:55:55 ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.6.4.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1861) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot1102.jar:git-Spigot-850da7e-b5fb9a1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException

**Comment by SilverHuskey** [comment]
Your config has some kind of error
