### ISSUE TITLE
Cannot obtain books in survival

### ISSUE THREAD

**Issue by radiodrag** [kicjow/Crazy-Enchantments#178]
Players can't receive books in survival mode but works in creative mode.
Heres what it print when i try to get a book in survival:
[16:19:02] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1839) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at me.badbones69.crazyenchantments.api.currencyapi.Currency.isCurrency(Currency.java:28) ~[?:?]
	at me.badbones69.crazyenchantments.controlers.ShopControler.onInvClick(ShopControler.java:189) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor739.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-R0.1-SNAPSHOT_19Fev2016.jar:git-Spigot-d4f98a3-4448a7e]
	... 15 more

**Comment by kicjow** [comment]
Please pastebin your config. It isnt setup to the newest version that is why.

**Comment by radiodrag** [comment]
ok, i'll try to make it generate a new file...
Yup, that was it, thanks!

**Comment by kicjow** [comment]
Np, if this gets fixed make sure to close the issue.
