### ISSUE TITLE
Items disappearing in trade

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#2]
It seems that items that I click into the trading GUI disappear, instead of becoming trades :P

**Comment by Yukun99** [comment]
[20:56:07 ERROR]: Could not pass event InventoryClickEvent to SwarmEnchantments v1.2org.bukkit.event.EventException	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]Caused by: java.lang.NullPointerException

**Comment by Yukun99** [comment]
That's the error if I try putting an invalid item in, but there's an error if I put the right item in too

**Comment by Yukun99** [comment]
[21:00:33] [Server thread/INFO]: xu_yukun issued server command: /tinker
[21:00:34] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SwarmEnchantments v1.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at me.BadBones69.CrazyEnchantments.Api.makeItem(Api.java:220) ~[?:?]
	at me.BadBones69.CrazyEnchantments.DustControl.getDust(DustControl.java:137) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Tinkerer.onInvClick(Tinkerer.java:124) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
	... 15 more

**Comment by Yukun99** [comment]
^That's the error for if I put a correct item in, and it disappears

**Comment by kicjow** [comment]
Ok well 1st question did you rename the plugin to SwarmEnchantments or is that a different plugin. 2nd is the error is happening because the dust id you put in is invalid. Meaning thats not the id for it.

**Comment by Yukun99** [comment]
I did rename the plugin in the code, and I put in a book, not dust :(

**Comment by Yukun99** [comment]
thanks also :D

**Comment by Yukun99** [comment]
How do I fix this though? I just copy and pasted the updated code into my edited code

**Comment by Yukun99** [comment]
Oh wait I saw it, my config was wrong, thanks :P

**Comment by Yukun99** [comment]
Although when I right click the dust now, I don't get anything :P, I rightclicked over a stack, and still got nothing. I used fire charges as the material btw.

**Comment by kicjow** [comment]
I am not sure what your saying the problem is.

**Comment by Yukun99** [comment]
basically when I click the mystery dust, I don't get the fixing or other dust

**Comment by kicjow** [comment]
Strange. Any errors ?

**Comment by Yukun99** [comment]
I'll go look :D

**Comment by Yukun99** [comment]
[11:45:34 ERROR]: Could not pass event PlayerInteractEvent to SwarmEnchantments v1.2org.bukkit.event.EventException	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:717) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]Caused by: java.lang.NumberFormatException: For input string: ""	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_91]	at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_91]	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_91]	at me.BadBones69.CrazyEnchantments.DustControl.getPercent(DustControl.java:165) ~[?:?]	at me.BadBones69.CrazyEnchantments.DustControl.openDust(DustControl.java:104) ~[?:?]	at sun.reflect.GeneratedMethodAccessor160.invoke(Unknown Source) ~[?:?]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]	... 18 more

**Comment by Yukun99** [comment]
very much error D:

**Comment by Yukun99** [comment]
it uses the item, just doesn't return anything.

**Comment by kicjow** [comment]
Hmm go to your config.yml and for the MysteryDust it looks like your Lore is missing the %Percent% and it needs that in there

**Comment by Yukun99** [comment]
ah thanks :D

**Comment by Yukun99** [comment]
Wow you read these things well... I'm absolutely useless at this haha.

**Comment by kicjow** [comment]
You mean the errors?

**Comment by Yukun99** [comment]
Yeah haha

**Comment by Yukun99** [comment]
I can only find what line the error is talking about, but never why it is doing that.

**Comment by kicjow** [comment]
Lol just look at the lines and see what happens. It says the problem is on line 165 [Here](https://github.com/kicjow/Crazy-Enchantments/blob/master/src/me/BadBones69/CrazyEnchantments/DustControl.java#L165) so it says the error is that all that is getting through is "" which the string called args is being returned there. args when made = "" and it should not be that when returned when going through the lore. it should be a number where %Percent% is. but since its returning "" that most likly means that the lore doesn't contain %Percent%

**Comment by kicjow** [comment]
If you understand what i am saying.

**Comment by Yukun99** [comment]
Ah I see... thanks so much haha. I only know elementary java, so a lot of this is gibberish to me XD
