### ISSUE TITLE
Error when opening creative inventory

### ISSUE THREAD

**Issue by Mavhill** [kicjow/Crazy-Enchantments#205]
Getting this error spaming counsel when you open up creative inventory. 

[16:26:21] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to CrazyEnchantments v1.7.9.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1988) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_20]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_20]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
Caused by: java.lang.NullPointerException
	at me.badbones69.crazyenchantments.Methods.makeItem(Methods.java:376) ~[?:?]
	at me.badbones69.crazyenchantments.controlers.Scrambler.getScramblers(Scrambler.java:109) ~[?:?]
	at me.badbones69.crazyenchantments.controlers.Scrambler.onReRoll(Scrambler.java:45) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_20]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-latest%201.11.2.jar:git-Spigot-d4f98a3-4448a7e]

**Comment by kicjow** [comment]
Pastebin your config for me.

**Comment by Mavhill** [comment]
[config.txt](https://github.com/kicjow/Crazy-Enchantments/files/1050252/config.txt)

**Comment by Mavhill** [comment]
Dude i re generated the config and duh no errors now.  Ignore the problem its mine. Sorry for wasting your time. Well done plug btw.

**Comment by kicjow** [comment]
Ah, thanks.
