### ISSUE TITLE
Command Erros

### ISSUE THREAD

**Issue by IsGeorgeCurious** [kicjow/Crazy-Enchantments#212]
Hello!
I have started using your plugin and I keep getting this error when running the commands.
`[12:21:00 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ce' in plugin CrazyEnchantments v1.7.9.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:765) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1047) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:884) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.NullPointerException
        at me.badbones69.crazyenchantments.api.currencyapi.CurrencyAPI.getCurrency(CurrencyAPI.java:18) ~[?:?]
        at me.badbones69.crazyenchantments.controlers.ShopControler.openGUI(ShopControler.java:49) ~[?:?]
        at me.badbones69.crazyenchantments.Main.onCommand(Main.java:194) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest%20(2).jar:git-PaperSpigot-1f7d532]
        ... 13 more
`
If you could please help me fix this error it would be greatly appreciated.
Thanks!

**Comment by kicjow** [comment]
Seems your trying to use the Vault currency without having vault installed. Install vault and it should work. If you dont want to use vault currency which is basicly ess money. Then go into the config.yml and change all the Currency: Vault options to either XP_Level or XP_Total.

**Comment by IsGeorgeCurious** [comment]
Ok thank you
