### ISSUE TITLE
Tinkerer Error

### ISSUE THREAD

**Issue by TheKillHDmc** [kicjow/Crazy-Enchantments#222]
Hello,

Sorry for my english, I speak French.

i have this error when i try to use Tinkerer : 

https://pastebin.com/

https://i.gyazo.com/543f81bff0040280303f1565cd2214a5.gif

Thanks for your help

**Comment by kicjow** [comment]
Lol, you sent the link to pastebin. I need the actual link to the file on pastebin. Make sure to paste the error then hit create a paste and then send the URL of the page it sends you to.

**Comment by TheKillHDmc** [comment]
Fuck x)


[17:09:38] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.9.2.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.badbones69.crazyenchantments.api.currencyapi.Currency.getCurrency(Currency.java:44) ~[?:?]
	at me.badbones69.crazyenchantments.controlers.Tinkerer.onInvClick(Tinkerer.java:97) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor391.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot.jar:git-PaperSpigot-"8b18730"]
	... 16 more

**Comment by kicjow** [comment]
The tinker file seems to be broken. Can you pastebin that? And make sure you use pastebin and not just paste it here.

**Comment by TheKillHDmc** [comment]
Fixed, i regenerated tinker.yml, thanks :)

**Comment by kicjow** [comment]
Np
