### ISSUE TITLE
Is this related to the compatibility with AAC? PlayerViolationEvent

### ISSUE THREAD

**Issue by mokdennie26** [kicjow/Crazy-Enchantments#236]
Personally, I have been using the Crazy_Enchantments with AAC for a long time and There is nothing going wrong hahah! Until recently, I have updated to the latest version of Crazy Enchant as well as the AAC, I started to get the following errors: (May be it is nothing big, but I decided to submit this issue , may be it is something big, i dk xd)

=======================================================================

[19:52:58] [Server thread/ERROR]: Could not pass event PlayerViolationEvent to CrazyEnchantments v1.7.9.2.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at me.konsolas.iaac.b.a(b.java:18) ~[?:?]
	at me.konsolas.aac.au.a(au.java:29) ~[?:?]
	at me.konsolas.aac.A.lambda$onPacketReceiving$1(A.java:91) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at me.badbones69.crazyenchantments.multisupport.AACSupport.isExempted(AACSupport.java:31) ~[?:?]
	at me.badbones69.crazyenchantments.multisupport.AACSupport.onViolation(AACSupport.java:46) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor405.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	... 13 more

=======================================================================

The above errors repeat for 20 times and keep on spamming. 
Sorry to bother you and I hope I have not disturbed you haha. 
Thanks for your time.

A little bit info:
CrazyEnchantments v1.7.9.2.4
Spigot 1.8.8 R0.1 Snapshot
Advanced Anticheat 3.2.2-b1

Best wishes

**Comment by kicjow** [comment]
Strange, not sure why it was happening but it has been fixed and will be in the next update.
