### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by alien4rmspace** [kicjow/Crazy-Enchantments#25]
I've been getting this error on my server recently
[02:51:40] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CrazyEnchantments v1.6.2.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:945) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_77]
	at me.BadBones69.CrazyEnchantments.Api.percentPick(Api.java:635) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Controlers.DustControl.openDust(DustControl.java:109) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
	... 18 more

**Comment by Yukun99** [comment]
I think I got this error before, or smth similar. Did you remove %percent% from your mystery dust lore XD

**Comment by alien4rmspace** [comment]
I removed the 1- from  '&a1-%Percent%% &7will be on a'

**Comment by Yukun99** [comment]
Np XD

**Comment by Yukun99** [comment]
The %percent% has to be in the lore or it will error
