### ISSUE TITLE
Could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by kjh16** [kicjow/Crazy-Enchantments#27]
http://hastebin.com/wesuyuyata.avrasm

`[18:44:53] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to CrazyEnchantments v1.6.2.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:773) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133) ~[?:1.8.0_72]
	at me.BadBones69.CrazyEnchantments.Enchantments.Helmets.onMovment(Helmets.java:64) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paperspigot.jar:git-PaperSpigot-"ee63dbe"]
	... 16 more`

**Comment by kicjow** [comment]
Thank you I'll look into it

**Comment by kicjow** [comment]
It seems if you go into your enchantments.yml your Commander enchantment is either missing or he name is set to blank. Make sure your don't remove enchantments from that file.

**Comment by kicjow** [comment]
Closed for now. Please make a new error if you still dont have a fix.
