### ISSUE TITLE
Bug when player buy a book legendary.

### ISSUE THREAD

**Issue by Tissandre** [kicjow/Crazy-Enchantments#277]
Hi, i make the last update. 1.7.9.3.3
And when player try to buy book legendary 100 lvl, players loose 100 lvl but dont have a book.

`[18:10:23] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.9.3.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1851) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [Pspigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_144]
	at me.badbones69.crazyenchantments.controlers.EnchantmentControl.powerPicker(EnchantmentControl.java:408) ~[?:?]
	at me.badbones69.crazyenchantments.controlers.EnchantmentControl.getRandomEnchantment(EnchantmentControl.java:56) ~[?:?]
	at me.badbones69.crazyenchantments.controlers.EnchantmentControl.pick(EnchantmentControl.java:370) ~[?:?]
	at me.badbones69.crazyenchantments.controlers.ShopControler.onInvClick(ShopControler.java:78) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Pspigot.jar:git-Spigot-798f32d-0cd0397]
	... 15 more`

**Comment by Tissandre** [comment]
Fixed.
