### ISSUE TITLE
[16:08:03 ERROR]: Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.7.9.3.3

### ISSUE THREAD

**Issue by Etrail** [kicjow/Crazy-Enchantments#290]
[16:08:03 ERROR]: Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.7.9.3.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:539) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:452) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:571) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1101) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:860) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:742) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:498) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1080) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1331) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:709) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:612) [spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
        at me.badbones69.crazyenchantments.multisupport.WorldGuard.allowsPVP(WorldGuard.java:16) ~[?:?]
        at me.badbones69.crazyenchantments.multisupport.Support.allowsPVP(Support.java:139) ~[?:?]
        at me.badbones69.crazyenchantments.api.CustomEnchantments.onHit(CustomEnchantments.java:270) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor196.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-PaperSpigot-7f032d5-e91aed8]
        ... 26 more

**Comment by kicjow** [comment]
World guard plugin is out of date.
