### ISSUE TITLE
entitydamagebyentityevent

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#34]
[14:43:44 ERROR]: Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.2.4org.bukkit.event.EventException	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:242) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]Caused by: java.lang.NullPointerException	at me.BadBones69.CrazyEnchantments.Enchantments.Bows.onArrowDamage(Bows.java:132) ~[?:?]	at sun.reflect.GeneratedMethodAccessor276.invoke(Unknown Source) ~[?:?]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]	... 22 more>

**Comment by kicjow** [comment]
This will has been fixed and will be in the the v1.6.2.6. Make sure you update also @Yukun99 since ur 1 version behind i see.

**Comment by Yukun99** [comment]
xie xie
