### ISSUE TITLE
Error in console during startup

### ISSUE THREAD

**Issue by MidnightSugar** [kicjow/Crazy-Enchantments#36]
I get the following error in the console when I start up CE.  I am using spigot 1.10 Buildtools: 52. 
The plugin itself works fine in-game. I see something about SilkSpawners in the error, but do not have it installed.

`[22:40:07] [Server thread/ERROR]: Error occurred while enabling CrazyEnchantments v1.6.3 (Is it up to date?)
java.lang.NoClassDefFoundError: de/dustplanet/util/SilkUtil
	at me.BadBones69.CrazyEnchantments.MultiSupport.SilkSpawners.<init>(SilkSpawners.java:16) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Main.onEnable(Main.java:72) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.ClassNotFoundException: de.dustplanet.util.SilkUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.10_BT52_06_12.jar:git-Spigot-3ccadba-7f1a322]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
	... 13 more`

**Comment by Yukun99** [comment]
silkspawners is a dependant of CE, you require it to run CE

**Comment by Yukun99** [comment]
if not u get errors

**Comment by MidnightSugar** [comment]
The mods seems to be running fine right now. Is this a critical error or can I ignore it? Which features of the mod need silkspawners to run?

**Comment by Yukun99** [comment]
just if u need telepathy to mine spawners

**Comment by MidnightSugar** [comment]
Ok thanks

**Comment by kicjow** [comment]
It is not required. Although I have to go back and make it not give that error so I'll fix that soon
