### ISSUE TITLE
Book isn't give after  payment of XP

### ISSUE THREAD

**Issue by Evolien** [kicjow/Crazy-Enchantments#38]
Hello.

There is a problem with the sign shop.
When somebody try to buy a book with the differents shop signs and categories,  The xp is payed 
(so for exemple the user have now 0 XP because he payed 15XP to buy the book") 
But ! The book isn't give to the user...

Can you help me please?

PS: Sorry for english

**Comment by kicjow** [comment]
There mite be an error in console. Please check that. Also what version of MC is your server. Expamle: Spigot v1.8.8

**Comment by Evolien** [comment]
Hello.

I use spigot 1.9 precisely. and there is an error:

 Could not pass event PlayerInteractEvent to CrazyEnchantments v1.6.3.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_91]
        at me.BadBones69.CrazyEnchantments.ECControl.Enchants(ECControl.java:41) ~[?:?]
        at me.BadBones69.CrazyEnchantments.ECControl.pick(ECControl.java:226) ~[?:?]
        at me.BadBones69.CrazyEnchantments.Controlers.SignControl.onPlayerInteract(SignControl.java:251) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        ... 17 more

Any Idea?

**Comment by kicjow** [comment]
Hmm it seams you mite not have any enchantments added into that Category of the sign.

**Comment by Evolien** [comment]
D'accord merci beaucoup :D

**Comment by Evolien** [comment]
Hello . So i change the name of categories and also add enchants in the categories 
("usuelle" , i add the enchant glowing in "usuelle") but:/

org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at me.BadBones69.CrazyEnchantments.ECControl.Enchants(ECControl.java:21) ~[?:?]
        at me.BadBones69.CrazyEnchantments.ECControl.pick(ECControl.java:226) ~[?:?]
        at me.BadBones69.CrazyEnchantments.Controlers.SignControl.onPlayerInteract(SignControl.java:251) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        ... 17 more

pls :/ can you help me ?

**Comment by kicjow** [comment]
It seems your enchantments file is empty.  If not pastebin the file and post the link

**Comment by Evolien** [comment]
I upload the file

**Comment by kicjow** [comment]
I said paste the url to it in this

**Comment by Evolien** [comment]
I change the format because the site don't accept .YML
[PDF.pdf](https://github.com/kicjow/Crazy-Enchantments/files/319944/PDF.pdf)

**Comment by kicjow** [comment]
I recommend deleting the Enchantments.yml then reload the server and then see if it works now.

**Comment by Evolien** [comment]
ok i try .

**Comment by Evolien** [comment]
Ok i reset the plugin and it work :/ so i think i will restart to configure it . Thank you .
