### ISSUE TITLE
Bug signs:  give book but without paying...

### ISSUE THREAD

**Issue by Evolien** [kicjow/Crazy-Enchantments#39]
Hello. Can you help me :/ 

[04:16:56 ERROR]: Could not pass event PlayerInteractEvent to CrazyEnchantments v1.6.3.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_91]
        at me.BadBones69.CrazyEnchantments.ECControl.Enchants(ECControl.java:41) ~[?:?]
        at me.BadBones69.CrazyEnchantments.ECControl.pick(ECControl.java:226) ~[?:?]
        at me.BadBones69.CrazyEnchantments.Controlers.SignControl.onPlayerInteract(SignControl.java:251) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-2038f4a-cd36f6f]
        ... 17 more

Thank you.

**Comment by kicjow** [comment]
It seems you have a sign set with a category on it but that category doesn't have any enchantments in it.

**Comment by Evolien** [comment]
Yes there are enchantments in the category.
Because when i bought with the sign i get the book ?

**Comment by kicjow** [comment]
I just checked the code and I see I didn't update Signs to work with the new way the Cost for Enchantment Books works. Thanks for the report it will be fixed in the next update.
