### ISSUE TITLE
[19:00:25 ERROR]: Could not pass event Player(Anything)Event to CrazyEnchantments v1.6.4.1 org.bukkit.event.EventException | Please Help

### ISSUE THREAD

**Issue by CreativeCreeeper** [kicjow/Crazy-Enchantments#59]
So, I Changed the "Enchantments Folder" Around to match my needs, and everything works fine except for when people move, try to apply and enchant in creative and survival and possible others. I was wondering if you could tell me whats going on or whats happening and what i messed up if anything. This may or may not be my fault because im a pretty sure i followed all the coding in the correct way. (Great Plugin Btw, Very Useful just the flooding of my command prompt is not assuring, and i need some help)
Here is the error:
-----------------------------------------------------------------------------------------------------------------
[19:00:25 ERROR]: Could not pass event PlayerMoveEvent to CrazyEnchantments v1.6.4.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5818108-f87cd1a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5818108-f87cd1a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:271) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
        at java.lang.String.contains(Unknown Source) ~[?:1.8.0_73]
        at me.BadBones69.CrazyEnchantments.API.CrazyEnchantments.hasEnchantments(CrazyEnchantments.java:92) ~[?:?]
        at me.BadBones69.CrazyEnchantments.Enchantments.Armor.onMovment(Armor.java:456) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-5818108-f87cd1a]
        ... 15 more
((Another Error))
-----------------------------------------------------------------------------------------------------------------
[19:14:58 ERROR]: Could not pass event InventoryCreativeEvent to CrazyEnchantments v1.6.4.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5818108-f87cd1a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5818108-f87cd1a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1750) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
        at java.lang.String.contains(Unknown Source) ~[?:1.8.0_73]
        at me.BadBones69.CrazyEnchantments.Api.getEnchAmount(Api.java:585) ~[?:?]
        at me.BadBones69.CrazyEnchantments.GUI.addEnchantment(GUI.java:470) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-5818108-f87cd1a]
        ... 15 more
[19:15:01 INFO]: CreativeCreeeper issued server command: /gamemode s
[19:15:03 ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.6.4.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-5818108-f87cd1a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-5818108-f87cd1a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1604) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-5818108-f87cd1a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException

**Comment by CreativeCreeeper** [comment]
Sorry Im New but i dont know if its illigal to double post or anything like that, but the name of my plugin was incorrect and it seems the only thing wrong is now the moving issue.

**Comment by kicjow** [comment]
Hmm looking at these errors it seems you need to go into your Enchantments.yml file and check if you have all the enchantments. It seems you are missing on. If you want me to check if you are just pastebin your Enchantments.yml file and paste the link here and ill look over it.

**Comment by CreativeCreeeper** [comment]
Ok, Thanks, actually last night i re-coded everything i did the day before. An Hour and a haklf of changing the specific tiers and colors to match my needs. And i fixed it myself. Im guessing it was my error and I deleted a colon or something. It is fixed now, but thanks anyway, I didn't close the post yet because i fixed it this morning (In my time zone).

**Comment by kicjow** [comment]
Lol that isn't coding. Its just configuring.

**Comment by Yukun99** [comment]
Savage badbones
