### ISSUE TITLE
citizensnpcs

### ISSUE THREAD

**Issue by zsgaming** [kicjow/Crazy-Enchantments#62]
[Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.4.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:847) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:772) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:500) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.citizensnpcs.nms.v1_10_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:122) [citizens-2.0.20.jar:?]
	at net.minecraft.server.v1_10_R1.EntityHuman.attack(EntityHuman.java:1009) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.EntityPlayer.attack(EntityPlayer.java:1136) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1578) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
	at me.BadBones69.CrazyEnchantments.MultiSupport.FactionsSupport.isFriendly(FactionsSupport.java:17) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Api.isFriendly(Api.java:228) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Enchantments.Swords.onPlayerDamage(Swords.java:37) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
	... 27 more

**Comment by Yukun99** [comment]
Prolly cos the citizens npcs are not in any faction.
