### ISSUE TITLE
error when doing /ce book from console

### ISSUE THREAD

**Issue by Yukun99** [kicjow/Crazy-Enchantments#7]
I used the console to give myself a CE book, but it gave me errors. I'm doing this as a crate plugin can only give books via commands. How do I solve this? The line of code it's having an error on is very weird, it's the line that goes `					if(lvl.equals("6"))lvl="VI";`, and I've already added all the enchants that I have removed to the plugin, other issues have all been fixed. The crate plugin is cosmicchest btw.
[21:19:45 WARN]: Unexpected exception while parsing console command "ce book Obliterate 1 1 xu_yukun"org.bukkit.command.CommandException: Unhandled exception executing command 'ce' in plugin SwarmEnchantments v1.2	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player	at me.BadBones69.CrazyEnchantments.Main.onCommand(Main.java:363) ~[?:?]	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-db6de12-18fbb24]	... 8 more>

**Comment by kicjow** [comment]
I'll look into it.

**Comment by kicjow** [comment]
Thank you has been fixed and will be in the next update.
