### ISSUE TITLE
Could not pass event InventoryClickEvent to CrazyEnchantments v1.6.5

### ISSUE THREAD

**Issue by leduyphuongcm** [kicjow/Crazy-Enchantments#73]
[07:32:19 ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.6.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar
:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:g
it-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar
:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar
:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1852) [spigot.jar:g
it-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spi
got-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spi
got-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-S
pigot-e000104-4cb3258]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-e000104-
4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-
Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-
Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-
Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:gi
t-Spigot-e000104-4cb3258]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
        at me.BadBones69.CrazyEnchantments.GUI.addEnchantment(GUI.java:481) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor227.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar
:git-Spigot-e000104-4cb3258]
        ... 15 more

**Comment by kicjow** [comment]
Thank you for the report. Ill make sure to fix this in the next update.

**Comment by kicjow** [comment]
Can you explain how this happens?
