### ISSUE TITLE
"An internal error occurred while attempting to perform this command" /ce add/remove 

### ISSUE THREAD

**Issue by IAmTheGoat** [kicjow/Crazy-Enchantments#86]
I'm having this problem when I fight with mobs at some time players, mobs and drops just freezes in my screen but other players can see them moving and can play the game. The problem disappears when I rejoin the server but it will come back when I fight whit mobs again. So I tried to fix this by removing some enchantments from my sword that could cause this problem but when I try to perform this command /ce remove "enchantment" I just get this "An internal error occurred while attempting to perform this command". Please can someone help me! Thank you! :)

**Comment by Yukun99** [comment]
Go read your logs and see if there are error messages. This doesn't help anything.

**Comment by IAmTheGoat** [comment]
Well It's pretty long... but here it is

[23:05:35] [Server thread/ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event PlayerMoveEvent to CrazyEnchantments v1.6.5
org.bukkit.event.EventException
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:607) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [craftbukkit.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException

**Comment by Yukun99** [comment]
There is a NullPointerException, you must have left something empty in one of the configs. Go check through them, cos this error log doesn't say anything about what's erroring in CE.

**Comment by ScrydanBiringer** [comment]
I was going to make an issue (still might, so its easier to find) but I could put it here (to the freezing issue, not the command problem).


If it was like me (relating to one of the sword enchantments causing things to "freeze") then it is the paralyze enchantment. I have found it by process of elimination on the enchants I had on my sword (I had many, lol).

What happens is when I use it, lightning strikes and then exp orbs no longer collect, and mob AI appears to be broken; even though in reality this is not the case.

This also was without the stormcaller enchantment on any armor. And it appears that lightning summoned through that enchant has no problem.

However, unlike the OP, I do not have problems with the commands.

**Comment by kicjow** [comment]
If still having a problem in the next update please make a new issue.
